server:
  port: 9229

spring:
  jersey:
    application-path: api/crypto/v1

app:
  version: 1.0.0

schedules:
  report:
    cron: 0 15 16 * * *

coinbase:
  apiKey: replace-with-api-key
  baseUrl: replace-with-url
  secretKey: replace-with-secret

poloniex:
  apiKey: replace-with-api-key
  baseUrl: replace-with-url
  secretKey: replace-with-secret

quadrigacx:
  apiKey: replace-with-api-key
  baseUrl: replace-with-url
  secretKey: replace-with-secret
