server:
  port: 9229

spring:
  jersey:
    application-path: api/crypto/v1

app:
  version: 1.0.0

schedules:
  report:
    cron: 0 15 16 * * *

coinbase:
  api-key: replace-with-api-key
  secret: replace-with-secret

poloniex:
  api-key: replace-with-api-key
  secret: replace-with-secret

quadrigacx:
  api-key: replace-with-api-key
  secret: replace-with-secret
