server:
  port: 9229
  compression:
    enabled: true
    mime-types: application/json

logging:
  config: config/logback.xml
  file: log/app.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  jersey:
    application-path: api/crypto/v1
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: false
    username: replace-with-email-username
    password: replace-with-email-password
#    test-connection: true

app:
  version: 1.0.0

schedules:
  report:
    cron: 0 15 16 * * *

MailingService:
  recipients:
    - replace-with-emails

bittrex:
  apiKey: replace-with-api-key
  baseUrl: https://bittrex.com/api/v1.1/
  secretKey: replace-with-secret

poloniex:
  apiKey: replace-with-api-key
  baseUrl: https://poloniex.com/
  secretKey: replace-with-secret

quadrigacx:
  apiKey: replace-with-api-key
  baseUrl: https://api.quadrigacx.com/v2/
  secretKey: replace-with-secret
