# General
server:
  port: 9229
  compression:
    enabled: true
    mime-types: application/json, text/plain

logging:
  config: classpath:config/logback.xml
  file: log/app.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jersey:
    application-path: api/crypto/v1
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: false
    username: replace-with-email-username
    password: replace-with-email-password
  mandatory-file-encoding: UTF-8

app:
  version: 1.0.0

# Analysis Service
alphavantage:
  apiKey: replace-with-api-key
  baseUrl: https://www.alphavantage.co/query

# Crypto Services
binance:
  apiKey: replace-with-api-key
  baseUrl: https://api.binance.com/api/
  secretKey: replace-with-secret

bitfinex:
  apiKey: replace-with-api-key
  baseUrl: https://api.bitfinex.com/
  secretKey: replace-with-secret

bittrex:
  apiKey: replace-with-api-key
  baseUrl: https://bittrex.com/api/v1.1/
  secretKey: replace-with-secret

poloniex:
  apiKey: replace-with-api-key
  baseUrl: https://poloniex.com/
  secretKey: replace-with-secret

quadrigacx:
  apiKey: replace-with-api-key
  baseUrl: https://api.quadrigacx.com/v2/
  secretKey: replace-with-secret

# Mail Service
schedules:
  report:
    cron: 0 15 16 * * *
mailing-service:
  recipients:
    - replace-with-emails

# News Service
news:
  twitter:
    consumerKey: replace-with-value
    consumerSecret: replace-with-value
    accessToken: replace-with-value
    accessTokenSecret: replace-with-value
    users:
      - replace-with-usernames

# Stock Service
questrade:
  apiKey: replace-with-api-key
  baseUrl: https://api01.iq.questrade.com/v1/
